# Generated by Django 4.1.7 on 2023-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercera_entregaApp', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_cafe',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tipo_cafe/'),
        ),
    ]
